name: Python Application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Setup python ${{matrix.python-version}}
      uses: actions/setup-pythonv3
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install flake8 pytest tox tox-gh-actions
        pip install -r requirements.txt
    - name: Test with tox
      run: tox

